version = 0.1

[default.global.parameters]
stack_name = "Floyd-LangGraphFunction-GefcykaLqwpD"

[default.build.parameters]
use_container = true

[default.deploy.parameters]
region = "us-east-1"
profile = "delve"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
